# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-21 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto_deploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=256, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('project_env', models.CharField(choices=[('dev_env', '\u7070\u5ea6\u53d1\u5e03'), ('pro_env', '\u6b63\u5f0f\u53d1\u5e03')], max_length=256, verbose_name='\u9879\u76ee\u73af\u5883')),
                ('project_language', models.CharField(choices=[('php', 'php'), ('java', 'java')], max_length=256, verbose_name='\u9879\u76ee\u8bed\u8a00')),
                ('code_env', models.CharField(choices=[('git', 'git'), ('svn', 'svn')], max_length=256, verbose_name='\u4ee3\u7801\u73af\u5883')),
                ('deploy_dir', models.CharField(max_length=256, verbose_name='\u53d1\u5e03\u5668\u5b58\u653e\u4ee3\u7801\u76ee\u5f55')),
                ('target_webroot', models.CharField(max_length=256, verbose_name='\u76ee\u6807\u4e3b\u673aweb\u6839\u76ee\u5f55')),
                ('target_server', models.CharField(max_length=256, verbose_name='\u76ee\u6807\u4e3b\u673a\u5730\u5740')),
                ('target_releases', models.CharField(max_length=256, verbose_name='\u76ee\u6807\u4e3b\u673a\u7248\u672c\u5e93\u76ee\u5f55')),
                ('publish_state', models.IntegerField(default=0, verbose_name='\u53d1\u5e03\u72b6\u6001')),
                ('publish_time', models.DateField(auto_now_add=True, max_length=256, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
            ],
        ),
    ]
